/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.mddarr.avromoviekafka.model.events.Event1;  
@SuppressWarnings("all")
/** Schema for hr.ivlahek.showcase.event.dto.Event1 */
@org.apache.avro.specific.AvroGenerated
public class Event1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Event1\",\"namespace\":\"com.mddarr.avromoviekafka.model.events.Event1\",\"doc\":\"Schema for hr.ivlahek.showcase.event.dto.Event1\",\"fields\":[{\"name\":\"name\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]},{\"name\":\"value\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String name;
  @Deprecated public java.lang.String value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public Event1() {}

  /**
   * All-args constructor.
   */
  public Event1(java.lang.String name, java.lang.String value) {
    this.name = name;
    this.value = value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.String)value$; break;
    case 1: value = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'value' field.
   */
  public java.lang.String getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.String value) {
    this.value = value;
  }

  /** Creates a new Event1 RecordBuilder */
  public static com.mddarr.avromoviekafka.model.events.Event1.Event1.Builder newBuilder() {
    return new com.mddarr.avromoviekafka.model.events.Event1.Event1.Builder();
  }
  
  /** Creates a new Event1 RecordBuilder by copying an existing Builder */
  public static com.mddarr.avromoviekafka.model.events.Event1.Event1.Builder newBuilder(com.mddarr.avromoviekafka.model.events.Event1.Event1.Builder other) {
    return new com.mddarr.avromoviekafka.model.events.Event1.Event1.Builder(other);
  }
  
  /** Creates a new Event1 RecordBuilder by copying an existing Event1 instance */
  public static com.mddarr.avromoviekafka.model.events.Event1.Event1.Builder newBuilder(com.mddarr.avromoviekafka.model.events.Event1.Event1 other) {
    return new com.mddarr.avromoviekafka.model.events.Event1.Event1.Builder(other);
  }
  
  /**
   * RecordBuilder for Event1 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Event1>
    implements org.apache.avro.data.RecordBuilder<Event1> {

    private java.lang.String name;
    private java.lang.String value;

    /** Creates a new Builder */
    private Builder() {
      super(com.mddarr.avromoviekafka.model.events.Event1.Event1.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.mddarr.avromoviekafka.model.events.Event1.Event1.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Event1 instance */
    private Builder(com.mddarr.avromoviekafka.model.events.Event1.Event1 other) {
            super(com.mddarr.avromoviekafka.model.events.Event1.Event1.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.String getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.mddarr.avromoviekafka.model.events.Event1.Event1.Builder setName(java.lang.String value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public com.mddarr.avromoviekafka.model.events.Event1.Event1.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'value' field */
    public java.lang.String getValue() {
      return value;
    }
    
    /** Sets the value of the 'value' field */
    public com.mddarr.avromoviekafka.model.events.Event1.Event1.Builder setValue(java.lang.String value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'value' field has been set */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'value' field */
    public com.mddarr.avromoviekafka.model.events.Event1.Event1.Builder clearValue() {
      value = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Event1 build() {
      try {
        Event1 record = new Event1();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.String) defaultValue(fields()[0]);
        record.value = fieldSetFlags()[1] ? this.value : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
