/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.mddarr.avromoviekafka;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserUpdateRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserUpdateRecord\",\"namespace\":\"com.mddarr.avromoviekafka\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"},{\"name\":\"eventName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String name;
  @Deprecated public java.lang.String eventName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public UserUpdateRecord() {}

  /**
   * All-args constructor.
   */
  public UserUpdateRecord(java.lang.String name, java.lang.String eventName) {
    this.name = name;
    this.eventName = eventName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return eventName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.String)value$; break;
    case 1: eventName = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'eventName' field.
   */
  public java.lang.String getEventName() {
    return eventName;
  }

  /**
   * Sets the value of the 'eventName' field.
   * @param value the value to set.
   */
  public void setEventName(java.lang.String value) {
    this.eventName = value;
  }

  /** Creates a new UserUpdateRecord RecordBuilder */
  public static com.mddarr.avromoviekafka.UserUpdateRecord.Builder newBuilder() {
    return new com.mddarr.avromoviekafka.UserUpdateRecord.Builder();
  }
  
  /** Creates a new UserUpdateRecord RecordBuilder by copying an existing Builder */
  public static com.mddarr.avromoviekafka.UserUpdateRecord.Builder newBuilder(com.mddarr.avromoviekafka.UserUpdateRecord.Builder other) {
    return new com.mddarr.avromoviekafka.UserUpdateRecord.Builder(other);
  }
  
  /** Creates a new UserUpdateRecord RecordBuilder by copying an existing UserUpdateRecord instance */
  public static com.mddarr.avromoviekafka.UserUpdateRecord.Builder newBuilder(com.mddarr.avromoviekafka.UserUpdateRecord other) {
    return new com.mddarr.avromoviekafka.UserUpdateRecord.Builder(other);
  }
  
  /**
   * RecordBuilder for UserUpdateRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserUpdateRecord>
    implements org.apache.avro.data.RecordBuilder<UserUpdateRecord> {

    private java.lang.String name;
    private java.lang.String eventName;

    /** Creates a new Builder */
    private Builder() {
      super(com.mddarr.avromoviekafka.UserUpdateRecord.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.mddarr.avromoviekafka.UserUpdateRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventName)) {
        this.eventName = data().deepCopy(fields()[1].schema(), other.eventName);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing UserUpdateRecord instance */
    private Builder(com.mddarr.avromoviekafka.UserUpdateRecord other) {
            super(com.mddarr.avromoviekafka.UserUpdateRecord.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.eventName)) {
        this.eventName = data().deepCopy(fields()[1].schema(), other.eventName);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.String getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public com.mddarr.avromoviekafka.UserUpdateRecord.Builder setName(java.lang.String value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public com.mddarr.avromoviekafka.UserUpdateRecord.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'eventName' field */
    public java.lang.String getEventName() {
      return eventName;
    }
    
    /** Sets the value of the 'eventName' field */
    public com.mddarr.avromoviekafka.UserUpdateRecord.Builder setEventName(java.lang.String value) {
      validate(fields()[1], value);
      this.eventName = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'eventName' field has been set */
    public boolean hasEventName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'eventName' field */
    public com.mddarr.avromoviekafka.UserUpdateRecord.Builder clearEventName() {
      eventName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public UserUpdateRecord build() {
      try {
        UserUpdateRecord record = new UserUpdateRecord();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.String) defaultValue(fields()[0]);
        record.eventName = fieldSetFlags()[1] ? this.eventName : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
